RepairIt/Models/Handyman.cs
namespace RepairIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Handyman
    {
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa miejscowości musi mieć długość od {2} do {1} znaków.")]
        public string City { get; set; }

        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa ulicy musi mieć długość od {2} do {1} znaków.")]
        public string Street { get; set; }

        [Required]
        [StringLength(4, MinimumLength = 1, ErrorMessage = "Numer domu musi mieć długość od {2} do {1} znaków.")]
        public string HomeNumber { get; set; }

        [Range(1, 999, ErrorMessage = "Numer lokalu musi mieć długość od {1} do {2} znaków.")]
        public short? FlatNumber { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime CreationDate { get; set; }

        [Required]
        [Range(1,1000, ErrorMessage = "Zasięg usług musi mieć wartość od {1} do {2} km.")]
        public short Radius { get; set; }

        [StringLength(200, MinimumLength = 5, ErrorMessage = "Opis musi mieć długość od {2} do {1} znaków.")]
        public string Description { get; set; }

        [Required]
        public virtual List<Service> Services { get; set; }

        [Required]
        public virtual User User { get; set; }
    }
}

RepairIt/Models/HandymanViewModel.cs
namespace RepairIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class HandymanViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa miejscowości musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Nazwa miejscowości")]
        public string City { get; set; }

        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa ulicy musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Nazwa ulicy")]
        public string Street { get; set; }

        [Required]
        [StringLength(4, MinimumLength = 1, ErrorMessage = "Numer domu musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Numer budynku")]
        public string HomeNumber { get; set; }

        [Range(1, 999, ErrorMessage = "Numer lokalu musi mieć długość od {1} do {2} znaków.")]
        [Display(Name = "Numer lokalu")]
        public short? FlatNumber { get; set; }

        [Required]
        [Range(1,100, ErrorMessage = "Zasięg usług musi mieć wartość od {1} do {2} km.")]
        [Display(Name = "Zasięg usługi [km]")]
        public short Radius { get; set; }

        [StringLength(200, MinimumLength = 5, ErrorMessage = "Opis musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Opis usługi")]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Data utworzenia usługi")]
        public DateTime CreationDate { get; set; }

        [Required]
        [Phone]
        public string PhoneNumber { get; set; }

        [Required]
        [Display(Name = "Typ usługi")]
        public List<string> Services { get; set; }

    }
}

RepairIt/Controllers/HandymanController.cs
namespace RepairIt.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using Models;
    using Service = Models.Service;

    public class HandymanController : Controller
    {
        public ActionResult Index(string message)
        {
            ViewBag.StatusMessage = message;

            var model = new HandymanMapViewModel
                        {
                            ServiceFilter = ""
                        };

            using (var dbContext = ApplicationDbContext.Create())
            {
                model.Handymen = dbContext.Handymen.Select(x => new HandymanViewModel
                                                                {
                                                                    Id = x.Id,
                                                                    City = x.City,
                                                                    Street = x.Street,
                                                                    HomeNumber = x.HomeNumber,
                                                                    FlatNumber = x.FlatNumber,
                                                                    Radius = x.Radius,
                                                                    Description = x.Description,
                                                                    CreationDate = x.CreationDate,
                                                                    Services = x.Services.Select(y => y.ServiceName).ToList(),
                                                                    PhoneNumber = x.User.PhoneNumber
                                                                }).ToList();
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(HandymanMapViewModel model)
        {
            List<HandymanViewModel> result;
            var service = model.ServiceFilter;

            using (var dbContext = ApplicationDbContext.Create())
            {
                if (service == Services.All)
                {
                    result = dbContext.Handymen.Select(x => new HandymanViewModel
                                                            {
                                                                Id = x.Id,
                                                                City = x.City,
                                                                Street = x.Street,
                                                                HomeNumber = x.HomeNumber,
                                                                FlatNumber = x.FlatNumber,
                                                                Radius = x.Radius,
                                                                Description = x.Description,
                                                                CreationDate = x.CreationDate,
                                                                Services = x.Services.Select(y => y.ServiceName).ToList(),
                                                                PhoneNumber = x.User.PhoneNumber
                                                            }).ToList();
                }
                else
                {
                    result = dbContext.Handymen.Where(x => x.Services.Select(y => y.ServiceName).FirstOrDefault() == service)
                                      .Select(x => new HandymanViewModel
                                                   {
                                                       Id = x.Id,
                                                       City = x.City,
                                                       Street = x.Street,
                                                       HomeNumber = x.HomeNumber,
                                                       FlatNumber = x.FlatNumber,
                                                       Radius = x.Radius,
                                                       Description = x.Description,
                                                       CreationDate = x.CreationDate,
                                                       Services = x.Services.Select(y => y.ServiceName).ToList(),
                                                       PhoneNumber = x.User.PhoneNumber
                                                   }).ToList();
                }
            }

            model.Handymen = result;
            model.ServiceFilter = "";

            if (!result.Any())
            {
                return RedirectToAction("Index", new {message = "Brak wyników - mapa nie została zmieniona"});
            }

            ViewBag.StatusMessage = "Wyświetlono przefiltrowane wyniki";

            return View(model);

        }

        [Authorize]
        public ActionResult AddHandyman()
        {
            var model = new HandymanViewModel();

            using (var dbContext = ApplicationDbContext.Create())
            {
                var id = User.Identity.GetUserId();
                var profile = dbContext.UsersProfile.FirstOrDefault(x => x.Id == id);

                model.PhoneNumber = profile?.PhoneNumber;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddHandyman(HandymanViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var dbContext = ApplicationDbContext.Create())
            {
                var userId = User.Identity.GetUserId();
                var user = dbContext.UsersProfile.FirstOrDefault(x => x.Id == userId);
                var handyman = new Handyman
                               {
                                   City = model.City,
                                   Street = model.Street,
                                   HomeNumber = model.HomeNumber,
                                   FlatNumber = model.FlatNumber,
                                   CreationDate = DateTime.Now.Date,
                                   Radius = model.Radius,
                                   Description = model.Description,
                                   Services = new List<Service>(),
                                   User = user
                               };

                foreach (var service in model.Services)
                {
                    var existingService = dbContext.Services.FirstOrDefault(x => x.ServiceName == service);

                    if (existingService == null)
                    {
                        var dbService = new Service
                                        {
                                            ServiceName = service
                                        };

                        dbContext.Services.Add(dbService);
                        handyman.Services.Add(dbService);
                    }
                    else
                    {
                        handyman.Services.Add(existingService);
                    }
                }

                dbContext.Handymen.Add(handyman);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index", new {message = "Usługa została pomyślnie dodana!"});
        }

        public ActionResult Details(Guid id)
        {
            HandymanViewModel model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var handyman = dbContext.Handymen.Select(x => new HandymanViewModel
                                                              {
                                                                  Id = x.Id,
                                                                  City = x.City,
                                                                  Street = x.Street,
                                                                  HomeNumber = x.HomeNumber,
                                                                  FlatNumber = x.FlatNumber,
                                                                  Radius = x.Radius,
                                                                  Description = x.Description,
                                                                  CreationDate = x.CreationDate,
                                                                  Services = x.Services.Select(y => y.ServiceName).ToList(),
                                                                  PhoneNumber = x.User.PhoneNumber
                                                              })
                                        .FirstOrDefault(x => x.Id == id);

                if (handyman == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", new {message = "Nie udało się uzyskać szczegółów usługi"});
                }

                model = handyman;
            }

            return View(model);
        }

        [Authorize]
        public ActionResult Edit(Guid id)
        {
            HandymanViewModel model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var handymanToEdit = dbContext.Handymen.FirstOrDefault(x => x.Id == id);

                if (handymanToEdit == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", "Manage", new {message = "Nie udało się przejść do edycji usługi"});
                }

                model = new HandymanViewModel
                        {
                            Id = handymanToEdit.Id,
                            City = handymanToEdit.City,
                            Street = handymanToEdit.Street,

RepairIt/Views/Handyman/AddHandyman.cshtml
@using RepairIt.Models
@model RepairIt.Models.HandymanViewModel

@{
    ViewBag.Title = "AddHandyman";
}

<style>
    body{
            color: #2D2C7A;
        }

    .btn-button{
        background-color: #2D2C7A;
        color: #DFB6FF;
        box-shadow: 0 0 0 1px #DFB6FF;
        border-radius: 50px;
        font-size: 15px;
        }

    .btn-button:hover{
        background-color: #DFB6FF;
        color: #2D2C7A;
        box-shadow: 0 0 0 1px #1A1A47;
        }
</style>

<div class="container body-content" style="justify-content: center;
                                                width: 1100px;">

    <div class="jumbotron" style="background-color: #AAA8FF;
                                       margin-top: 80px;
                                       border-radius: 100px;
                                       box-shadow: 0 0 1px 2px #2D2C7A;">

        <h2 class="row" style="text-align: center; margin-top: -20px; color: #2D2C7A; text-shadow: 1px 1px 2px #8483C7;">Dodaj swoją usługę</h2>
        <hr style="background-color: #2D2C7A; height: 1px; border: 0">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.PhoneNumber)

                <div class="form-group">
                    @Html.LabelFor(model => model.Services, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.ListBoxFor(model => model.Services, new SelectList(Services.GetServices()), new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Services, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.City, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Street, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Street, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Street, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HomeNumber, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HomeNumber, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.HomeNumber, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FlatNumber, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FlatNumber, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.FlatNumber, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Radius, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Radius, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Radius, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default btn-button" value="Dodaj usługę"/>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

@Html.ActionLink("Powrót do mapy usług", "Index", "Handyman", null, new {@class = "btn btn-default btn-button"})

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RepairIt/Views/Handyman/Details.cshtml
@model RepairIt.Models.HandymanViewModel

@{
    Layout = "";
    ViewBag.Title = "Usługa";
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@500&display=swap" rel="stylesheet">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <style>
        body{
            font-family: 'Work Sans', sans-serif;
            background-color: #F0D9FC;
            color: #2D2C7A;
            font-size: medium;
        }

        input[type=text], select{
            width: 60%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .navbar-brand{
            font-size: 40px;
        }

        .navbar-nav{
            size: 300px;
        }

        .text-size{
            font-size: 22px;
            margin-top: 20px;
            }

        .btn-left, .btn-right{
            background-color: #2D2C7A;
            color: #DFB6FF;
            box-shadow: 0 0 0 1px #DFB6FF;
            border-radius: 50px;
            font-size: 15px;
        }

        .btn-left:hover, .btn-right:hover{
            background-color: #DFB6FF;
            color: #2D2C7A;
            box-shadow: 0 0 0 1px #1A1A47;
        }

        th {
                text-align: center;
            }
    </style>

    <script>
        function initAutocomplete()
                {
                    var geocoder = new google.maps.Geocoder();
                    var model = @Html.Raw(Json.Encode(Model));
                    var address = model.City + ", " + model.Street + " " + model.HomeNumber + "/" + model.FlatNumber;
                    var radius = model.Radius;
                    var myCenter = new google.maps.LatLng(52.114444, 19.423333);
                    var map = new google.maps.Map(document.getElementById('map'), {
                        center: myCenter,
                        zoom: 10,
                        mapTypeId: 'roadmap',
                        styles: stylesArray,
                        options: {gestureHandling: 'greedy'}
                    });
                    var input = document.getElementById('pac-input');
                    var searchBox = new google.maps.places.SearchBox(input);
         
                    map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
         
                    map.addListener('bounds_changed', function ()
                    {
                        searchBox.setBounds(map.getBounds());
                    });

                    geocoder.geocode({ 'address': address }, function (results, status)
                    {
                        if (status === google.maps.GeocoderStatus.OK)
                        {
                            var latitude = results[0].geometry.location.lat();
                            var longitude = results[0].geometry.location.lng();
                            var cordinates = { lat: latitude, lng: longitude };
                            var marker = new google.maps.Marker({ position: cordinates, icon: 'http://maps.google.com/mapfiles/dir_walk_60.png', map: map });
                            var cityCircle = new google.maps.Circle({
                            strokeColor: "#2D2C7A",
                            strokeOpacity: 0.8,
                            strokeWeight: 2,
                            fillColor: "#DFB6FF",
                            fillOpacity: 0.3,
                            map: map,
                            center: { lat: latitude, lng: longitude},
                            radius: radius * 1000,
                            });

                            map.panTo(marker.getPosition());
                        }
                        else
                        {
                            console.log(status);
                        }
                    });
         
                    var markers = [];
         
                    searchBox.addListener('places_changed', function ()
                    {
                        var places = searchBox.getPlaces();
         
                        if (places.length === 0)
                        {
                            return;
                        }
         
                        markers.forEach(function (marker)
                        {
                            marker.setMap(null);
                        });
         
                        markers = [];
                        var bounds = new google.maps.LatLngBounds();
         
                        places.forEach(function (place)
                        {
                            if (!place.geometry)
                            {
                                console.log("Returned place contains no geometry");
                                return;
                            }
         
                            if (place.geometry.viewport)
                            {
                                bounds.union(place.geometry.viewport);
                            }
                            else
                            {
                                bounds.extend(place.geometry.location);
                            }
                        });
         
                        map.fitBounds(bounds);
                    });
                }
    </script>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #2D2C7A; border-color: #2D2C7A">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Repair it!", "Index", "Home", new {area = ""}, new {@class = "navbar-brand", @style = "color: #DFB6FF; margin-top: 10%;margin-bottom: 10%;"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Strona główna", "Index", "Home", null, new {@class = "text-size", style = "color: #DFB6FF"})</li>
                <li>@Html.ActionLink("Zlecenia", "Index", "Offer", null, new {@class = "text-size", style = "color: #DFB6FF"})</li>
                <li>@Html.ActionLink("Usługi", "Index", "Handyman", null, new {@class = "text-size", style = "color: #DFB6FF"})</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

<div class="container body-content" style="justify-content: center;
                                               width: 1100px;">
    <div class="jumbotron" style="background-color: #AAA8FF;
                                          margin-top: 80px;
                                          border-radius: 100px;
                                          box-shadow: 0 0 1px 2px #2D2C7A;
                                      ">
        <div class="container" style="background-color: #EACFFF;
                                                                    border-radius: 70px;
                                                                    padding-bottom: 20px;
                                                                    padding-top: 20px;
                                                                    margin-bottom: 20px;
                                                                    box-shadow: 0 0 1px 1px #2D2C7A;">
            <br/>
            <h2 class="row" style="text-align: center; margin-top: -20px; color: #2D2C7A; text-shadow: 1px 1px 2px #8483C7;">Szczegóły</h2>
            <hr style="background-color: #2D2C7A; height: 1px; border: 0">

            <table class="table" style="text-align: center">
                <tr>
                    <th>
                        Numer kontaktowy
                    </th>

                    <th>
                        Data utworzenia
                    </th>

                    <th>
                        Typ usługi
                    </th>

                    <th>
                        Opis usługi
                    </th>

                    <th>
                        Adres
                    </th>

                </tr>
                <tr>
                    <td>
                        @Model.PhoneNumber.Substring(0, 3)-@Model.PhoneNumber.Substring(3, 3)-@Model.PhoneNumber.Substring(6, 3)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.CreationDate)
                    </td>

                    <td>
                        @foreach (var service in Model.Services)
                        {
                            @Html.DisplayFor(model => service)
                            @:
                        }
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Description)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.City) @Html.DisplayFor(model => model.Street) @Html.DisplayFor(model => model.HomeNumber)
                        @{
                            if (Model.FlatNumber != null)
                            {
                                @:m. @Html.DisplayFor(model => model.FlatNumber)
                            }
                        }
                    </td>
                </tr>
            </table>
        </div>

        <div>
            <input id="pac-input" type="text" placeholder="wyszukaj miejscowość">
            <div id="map" style="height:500px; border-radius: 30px;box-shadow: 1px 2px #2D2C7A;"></div>
        </div>
    </div>

    @Html.ActionLink("Powrót do mapy usług", "Index", "Handyman", null, new {@class = "btn btn-lg btn-right"})

    <hr style="background-color: #2D2C7A; height: 1px;">
    <footer>
        <p style="color: #2D2C7A;">&copy; @DateTime.Now.Year - Władowska Gabriela</p>
    </footer>
</div>
</body>
</html>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApZd7QUQCRUJ9r9bGcBVCDwwx-wPsSqpg&libraries=places&callback=initAutocomplete"></script>