RepairIt/Models/Offer.cs
namespace RepairIt.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class Offer
    {
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 5, ErrorMessage = "Tytuł musi mieć długość od {2} do {1} znaków.")]
        public string Title { get; set; }

        [Required]
        [StringLength(200, MinimumLength = 5, ErrorMessage = "Opis musi mieć długość od {2} do {1} znaków.")]
        public string Description { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa miejscowości musi mieć długość od {2} do {1} znaków.")]
        public string City { get; set; }

        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa ulicy musi mieć długość od {2} do {1} znaków.")]
        public string Street { get; set; }

        [Required]
        [StringLength(4, MinimumLength = 1, ErrorMessage = "Numer domu musi mieć długość od {2} do {1} znaków.")]
        public string HomeNumber { get; set; }

        [Range(1, 999, ErrorMessage = "Numer lokalu musi mieć długość od {1} do {2} znaków.")]
        public short? FlatNumber { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime CreationDate { get; set; }

        [Required]
        public virtual User User { get; set; }
    }
}

RepairIt/Models/OfferViewModel.cs
namespace RepairIt.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class OfferViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 5, ErrorMessage = "Tytuł musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Tytuł zlecenia")]
        public string Title { get; set; }

        [Required]
        [StringLength(200, MinimumLength = 5, ErrorMessage = "Opis musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Opis zlecenia")]
        public string Description { get; set; }

        [Required]
        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa miejscowości musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Nazwa miejscowości")]
        public string City { get; set; }

        [StringLength(40, MinimumLength = 2, ErrorMessage = "Nazwa ulicy musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Nazwa ulicy")]
        public string Street { get; set; }

        [Required]
        [StringLength(4, MinimumLength = 1, ErrorMessage = "Numer domu musi mieć długość od {2} do {1} znaków.")]
        [Display(Name = "Numer budynku")]
        public string HomeNumber { get; set; }

        [Range(1, 999, ErrorMessage = "Numer lokalu musi mieć długość od {1} do {2} znaków.")]
        [Display(Name = "Numer mieszkania")]
        public short? FlatNumber { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Data utworzenia zlecenia")]
        public DateTime CreationDate { get; set; }

        [Required]
        [Phone]
        public string PhoneNumber { get; set; }
    }
}

RepairIt/Controllers/OfferController.cs
namespace RepairIt.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Validation;
    using System.Linq;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using Models;

    public class OfferController : Controller
    {
        public ActionResult Index(string message)
        {
            ViewBag.StatusMessage = message;

            List<OfferViewModel> model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                model = dbContext.Offers.Select(x => new OfferViewModel
                                                     {
                                                         Id = x.Id,
                                                         Title = x.Title,
                                                         Description = x.Description,
                                                         City = x.City,
                                                         Street = x.Street,
                                                         HomeNumber = x.HomeNumber,
                                                         FlatNumber = x.FlatNumber,
                                                         CreationDate = x.CreationDate,
                                                         PhoneNumber = x.User.PhoneNumber
                                                     }).ToList();
            }
            return View(model);
        }

        [Authorize]
        public ActionResult AddOffer()
        {
            var model = new OfferViewModel();

            using (var dbContext = ApplicationDbContext.Create())
            {
                var id = User.Identity.GetUserId();
                var profile = dbContext.UsersProfile.FirstOrDefault(x => x.Id == id);

                model.PhoneNumber = profile?.PhoneNumber;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult AddOffer(OfferViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var dbContext = ApplicationDbContext.Create())
            {
                var id = User.Identity.GetUserId();
                var profile = dbContext.UsersProfile.FirstOrDefault(x => x.Id == id);
                var offer = new Offer
                            {
                                Title = model.Title,
                                Description = model.Description,
                                City = model.City,
                                Street = model.Street,
                                HomeNumber = model.HomeNumber,
                                FlatNumber = model.FlatNumber,
                                CreationDate = DateTime.Now.Date,
                                User = profile
                            };

                dbContext.Offers.Add(offer);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index", new {message = "Zlecenie zostało pomyślnie dodane!"});
        }

        public ActionResult Details(Guid id)
        {
            OfferViewModel model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var offer = dbContext.Offers.Select(x => new OfferViewModel
                                                         {
                                                             Id = x.Id,
                                                             Title = x.Title,
                                                             Description = x.Description,
                                                             City = x.City,
                                                             Street = x.Street,
                                                             HomeNumber = x.HomeNumber,
                                                             FlatNumber = x.FlatNumber,
                                                             CreationDate = x.CreationDate,
                                                             PhoneNumber = x.User.PhoneNumber
                                                         })
                                        .FirstOrDefault(x => x.Id == id);

                if (offer == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", new {message = "Nie udało się uzyskać szczegółów zlecenia."});
                }

                model = offer;
            }

            return View(model);
        }

        [Authorize]
        public ActionResult Edit(Guid id)
        {
            OfferViewModel model;

            using (var dbContext = ApplicationDbContext.Create())
            {
                var offerToEdit = dbContext.Offers.FirstOrDefault(x => x.Id == id);

                if (offerToEdit == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", "Manage", new {message = "Nie udało się przejść do edycji zlecenia."});
                }

                model = new OfferViewModel
                        {
                            Id = offerToEdit.Id,
                            Title = offerToEdit.Title,
                            Description = offerToEdit.Description,
                            City = offerToEdit.City,
                            Street = offerToEdit.Street,
                            HomeNumber = offerToEdit.HomeNumber,
                            FlatNumber = offerToEdit.FlatNumber,
                            CreationDate = offerToEdit.CreationDate,
                            PhoneNumber = offerToEdit.User.PhoneNumber
                        };
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(OfferViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                using (var dbContext = ApplicationDbContext.Create())
                {
                    var offerToEdit = dbContext.Offers.FirstOrDefault(x => x.Id == model.Id);

                    if (offerToEdit == null)
                    {
                        dbContext.Dispose();
                        return RedirectToAction("Index", "Manage", new {message = "Wystąpił błąd podczas edycji zlecenia."});
                    }

                    offerToEdit.City = model.City;
                    offerToEdit.Description = model.Description;
                    offerToEdit.Street = model.Street;
                    offerToEdit.Title = model.Title;
                    offerToEdit.FlatNumber = model.FlatNumber;
                    offerToEdit.HomeNumber = model.HomeNumber;

                    var userId = User.Identity.GetUserId();
                    offerToEdit.User = dbContext.UsersProfile.FirstOrDefault(x => x.Id == userId);

                    dbContext.SaveChanges();
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                                      eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                          ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }

            return RedirectToAction("Index", "Manage", new {message = "Zedytowano zlecenie"});
        }

        [Authorize]
        public ActionResult Delete(Guid id)
        {
            using (var dbContext = ApplicationDbContext.Create())
            {
                var offerToDelete = dbContext.Offers.FirstOrDefault(x => x.Id == id);

                if (offerToDelete == null)
                {
                    dbContext.Dispose();
                    return RedirectToAction("Index", "Manage", new {message = "Nie udało się usunąć zlecenia"});
                }

                dbContext.Offers.Remove(offerToDelete);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index", "Manage", new {message = "Zlecenie zostało usunięte"});
        }
    }
}

RepairIt/Views/Offer/AddOffer.cshtml
@model RepairIt.Models.OfferViewModel

@{
    ViewBag.Title = "AddOffer";
}

<style>
    body{
            color: #2D2C7A;
        }

    .btn-button{
        background-color: #2D2C7A;
        color: #DFB6FF;
        box-shadow: 0 0 0 1px #DFB6FF;
        border-radius: 50px;
        font-size: 15px;
        }

    .btn-button:hover{
        background-color: #DFB6FF;
        color: #2D2C7A;
        box-shadow: 0 0 0 1px #1A1A47;
        }
</style>

<div class="container body-content" style="justify-content: center;
                                                width: 1100px;">

    <div class="jumbotron" style="background-color: #AAA8FF;
                                       margin-top: 80px;
                                       border-radius: 100px;
                                       box-shadow: 0 0 1px 2px #2D2C7A;">

        <h2 class="row" style="text-align: center; margin-top: -20px; color: #2D2C7A; text-shadow: 1px 1px 2px #8483C7;">Dodaj swoje zlecenie</h2>
        <hr style="background-color: #2D2C7A; height: 1px; border: 0">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.PhoneNumber)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.City, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Street, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Street, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Street, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HomeNumber, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HomeNumber, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.HomeNumber, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FlatNumber, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FlatNumber, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.FlatNumber, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default btn-button" value="Dodaj zlecenie"/>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

@Html.ActionLink("Powrót do mapy zleceń", "Index", "Offer", null, new {@class = "btn btn-default btn-button"})


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RepairIt/Views/Offer/Details.cshtml
@model RepairIt.Models.OfferViewModel

@{
    Layout = "";
    ViewBag.Title = "Zlecenie";
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@500&display=swap" rel="stylesheet">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <style>
        body{
            font-family: 'Work Sans', sans-serif;
            background-color: #F0D9FC;
            color: #2D2C7A;
            font-size: medium;
        }

        input[type=text], select{
            width: 60%;
            padding: 12px 20px;
            margin: 8px 0;
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .navbar-brand{
            font-size: 40px;
        }

        .navbar-nav{
            size: 300px;
        }

        .text-size{
            font-size: 22px;
            margin-top: 20px;
            }

        .btn-left, .btn-right{
            background-color: #2D2C7A;
            color: #DFB6FF;
            box-shadow: 0 0 0 1px #DFB6FF;
            border-radius: 50px;
            font-size: 15px;
        }

        .btn-left:hover, .btn-right:hover{
            background-color: #DFB6FF;
            color: #2D2C7A;
            box-shadow: 0 0 0 1px #1A1A47;
        }

        th {
                text-align: center;
        }

    </style>

    <script>
        function initAutocomplete()
                {
                    var geocoder = new google.maps.Geocoder();
                    var model = @Html.Raw(Json.Encode(Model));
                    var address = model.City + ", " + model.Street + " " + model.HomeNumber + "/" + model.FlatNumber;
                    var myCenter = new google.maps.LatLng(52.114444, 19.423333);
                    var map = new google.maps.Map(document.getElementById('map'), {
                        center: myCenter,
                        zoom: 12,
                        mapTypeId: 'roadmap',
                        styles: stylesArray,
                        options: {gestureHandling: 'greedy'}
                    });
                    var input = document.getElementById('pac-input');
                    var searchBox = new google.maps.places.SearchBox(input);
         
                    map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);
         
                    map.addListener('bounds_changed', function ()
                    {
                        searchBox.setBounds(map.getBounds());
                    });
         
                    geocoder.geocode({ 'address': address }, function (results, status)
                    {
                        if (status === google.maps.GeocoderStatus.OK)
                        {
                            var latitude = results[0].geometry.location.lat();
                            var longitude = results[0].geometry.location.lng();
                            var cordinates = { lat: latitude, lng: longitude };
                            var marker = new google.maps.Marker({ position: cordinates, icon: 'http://maps.google.com/mapfiles/dir_walk_60.png', map: map });
         
                            map.panTo(marker.getPosition());
                        }
                        else
                        {
                            console.log(status);
                        }
                    });
         
                    var markers = [];
         
                    searchBox.addListener('places_changed', function ()
                    {
                        var places = searchBox.getPlaces();
         
                        if (places.length === 0)
                        {
                            return;
                        }
         
                        markers.forEach(function (marker)
                        {
                            marker.setMap(null);
                        });
         
                        markers = [];
                        var bounds = new google.maps.LatLngBounds();
         
                        places.forEach(function (place)
                        {
                            if (!place.geometry)
                            {
                                console.log("Returned place contains no geometry");
                                return;
                            }
         
                            if (place.geometry.viewport)
                            {
                                bounds.union(place.geometry.viewport);
                            }
                            else
                            {
                                bounds.extend(place.geometry.location);
                            }
                        });
         
                        map.fitBounds(bounds);
                    });
                }
    </script>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #2D2C7A; border-color: #2D2C7A">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Repair it!", "Index", "Home", new {area = ""}, new {@class = "navbar-brand", @style = "color: #DFB6FF; margin-top: 10%;margin-bottom: 10%;"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Strona główna", "Index", "Home", null, new {@class = "text-size", style = "color: #DFB6FF"})</li>
                <li>@Html.ActionLink("Zlecenia", "Index", "Offer", null, new {@class = "text-size", style = "color: #DFB6FF"})</li>
                <li>@Html.ActionLink("Usługi", "Index", "Handyman", null, new {@class = "text-size", style = "color: #DFB6FF"})</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

<div class="container body-content" style="justify-content: center;
                                               width: 1100px;">

    <div class="jumbotron" style="background-color: #AAA8FF;
                                          margin-top: 80px;
                                          border-radius: 100px;
                                          box-shadow: 0 0 1px 2px #2D2C7A;
                                      ">
        <div class="container" style="background-color: #EACFFF;
                                                                            border-radius: 70px;
                                                                            padding-bottom: 20px;
                                                                            padding-top: 20px;
                                                                            margin-bottom: 20px;
                                                                            box-shadow: 0 0 1px 1px #2D2C7A;">
            <br/>
            <h2 class="row" style="text-align: center; margin-top: -20px; color: #2D2C7A; text-shadow: 1px 1px 2px #8483C7;">Szczegóły</h2>
            <hr style="background-color: #2D2C7A; height: 1px; border: 0">

            <table class="table" style="text-align: center">
                <tr>
                    <th>
                        Numer kontaktowy
                    </th>

                    <th>
                        Data utworzenia
                    </th>

                    <th>
                        Tytuł zlecenia
                    </th>

                    <th>
                        Opis zlecenia
                    </th>

                    <th>
                        Adres zlecenia
                    </th>


                </tr>

                <tr>
                    <td>
                        @Model.PhoneNumber.Substring(0, 3)-@Model.PhoneNumber.Substring(3, 3)-@Model.PhoneNumber.Substring(6, 3)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.CreationDate)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Title)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Description)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.City) @Html.DisplayFor(model => model.Street) @Html.DisplayFor(model => model.HomeNumber)
                        @{
                            if (Model.FlatNumber != null)
                            {
                                @:m. @Html.DisplayFor(model => model.FlatNumber)
                            }
                        }
                    </td>
                </tr>
            </table>
        </div>
        <div>
            <input id="pac-input" type="text" placeholder="wyszukaj miejscowość">
            <div id="map" style="height:500px; border-radius: 30px;box-shadow: 1px 2px #2D2C7A;"></div>
        </div>
    </div>

    @Html.ActionLink("Powrót do mapy zleceń", "Index", "Offer", null, new {@class = "btn btn-lg btn-right"})

    <hr style="background-color: #2D2C7A; height: 1px;">
    <footer>
        <p style="color: #2D2C7A;">&copy; @DateTime.Now.Year - Władowska Gabriela</p>
    </footer>
</div>
</body>
</html>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyApZd7QUQCRUJ9r9bGcBVCDwwx-wPsSqpg&libraries=places&callback=initAutocomplete"></script>

RepairIt/Views/Offer/Edit.cshtml
@model RepairIt.Models.OfferViewModel

@{
    ViewBag.Title = "EditOffer";
}

<style>
    body{
            color: #2D2C7A;
            font-size: medium;
       }

    .btn-button{
        background-color: #2D2C7A;
        color: #DFB6FF;
        box-shadow: 0 0 0 1px #DFB6FF;
        border-radius: 50px;
        font-size: 15px;
        }

    .btn-button:hover{
        background-color: #DFB6FF;
        color: #2D2C7A;
        box-shadow: 0 0 0 1px #1A1A47;
        }
</style>


<div class="container body-content" style="justify-content: center;
                                                    width: 1100px;">
    <div class="jumbotron" style="background-color: #AAA8FF;
                                    margin-top: 80px;
                                    border-radius: 100px;
                                    box-shadow: 0 0 1px 2px #2D2C7A;">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <h2 class="row" style="text-align: center; margin-top: -20px; color: #2D2C7A; text-shadow: 1px 1px 2px #8483C7;">Edytuj swoje zlecenie</h2>
                <hr style="background-color: #2D2C7A; height: 1px; border: 0">
                @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.City, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Street, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Street, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.Street, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HomeNumber, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.HomeNumber, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.HomeNumber, "", new {@class = "text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FlatNumber, htmlAttributes: new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FlatNumber, new {htmlAttributes = new {@class = "form-control"}})
                        @Html.ValidationMessageFor(model => model.FlatNumber, "", new {@class = "text-danger"})
                    </div>
                </div>

                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreationDate)
                @Html.HiddenFor(model => model.PhoneNumber)

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-default btn-button" value="Zapisz"/>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@Html.ActionLink("Powrót do profilu", "Index", "Manage", null, new {@class = "btn btn-default btn-button"})

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}